import type { CncAxis } from './cncAnimationConfig'

export const CNC_MACHINING = {
  timings: {
    singleApproachDuration: 1.15,
    postContactCoolantDelay: 0.2,
    coolantRampInDuration: 0.5,
    workpieceSwapAfterCoolantStart: 1.25,
    occlusionRampBeforeSwap: 0.4,
    occlusionHoldAfterSwap: 0.18,
    occlusionRampOutDuration: 0.55,
    coolantRampOutAfterSwap: 0.95,
    coolantRampOutDuration: 0.7,
    spindleDecelerationAfterSwap: 1.15,
    spindleDecelerationDuration: 1.1,
    postMachiningRetractionHold: 0.5,
    interiorResultHoldDuration: 1.1,
    finishedInspectionHoldDuration: 1.25,
  },
  turret: {
    machiningOffsets: {
      x: 4,
      z: 2.5,
    } as Partial<Record<CncAxis, number>>,
    homeReturnDuration: 1.1,
  },
  chuck: {
    machiningRpmVisualSpeed: 60 / 1.6,
    inspectionRpmVisualSpeed: 4.5,
  },
  sparks: {
    particleCount: 56,
    spawnRate: 52,
    minimumLifetime: 0.2,
    maximumLifetime: 0.42,
    minimumSpeed: 16,
    maximumSpeed: 30,
    gravity: [0, -25, 0] as [number, number, number],
    color: '#ffc064',
    minimumSize: 0.65,
    maximumSize: 1,
  },
  coolant: {
    emitterPosition: [-7.5, 105, 70] as [number, number, number],
    sprayDirection: [0.25, -0.78, 0.42] as [number, number, number],
    jet: {
      particleCount: 120,
      gravity: [0, -12, 0] as [number, number, number],
      spread: 0.38,
      minimumSpeed: 36,
      maximumSpeed: 58,
      minimumLifetime: 0.24,
      maximumLifetime: 0.52,
      color: '#a9c5c8',
      minimumOpacity: 0.22,
      maximumOpacity: 0.66,
    },
    mist: {
      particleCount: 250,
      gravity: [0, -3.5, 0] as [number, number, number],
      spread: 1.65,
      minimumSpeed: 4,
      maximumSpeed: 11,
      minimumLifetime: 0.75,
      maximumLifetime: 1.45,
      color: '#c3d5d6',
      minimumOpacity: 0.16,
      maximumOpacity: 0.54,
      occlusionOpacityBoost: 0.24,
      minimumSize: 3.2,
      maximumSize: 7.8,
    },
    veil: {
      color: '#d4e0df',
      maximumOpacity: 0.46,
    },
    hotChips: {
      particleCount: 14,
      color: '#d6a56a',
      opacity: 0.64,
      size: 0.48,
      minimumLifetime: 0.16,
      maximumLifetime: 0.38,
      minimumSpeed: 8,
      maximumSpeed: 19,
      gravity: [0, -22, 0] as [number, number, number],
    },
  },
} as const
