export const VISUAL_CALIBRATION = {
  background: '#d8d7d1',
  renderer: {
    dpr: [1, 1.75] as [number, number],
    toneMappingExposure: 0.95,
  },
  camera: {
    fov: 34,
    direction: [1.15, 0.62, 1.3] as [number, number, number],
    desktopDistanceScale: 0.8,
    mobileDistanceScale: 1.08,
    mobileAspectThreshold: 0.85,
    nearDistanceDivisor: 100,
    farRadiusMultiplier: 8,
    heroIntroDistanceScale: 1.12,
    heroIntroDuration: 1.8,
    presetTransitionDuration: 0.9,
    dumanDirection: [0.6655, 0.2458, 0.7048] as [number, number, number],
    dumanTargetOffset: [4.5, 1.5, -4.25] as [number, number, number],
    dumanBadgeFitScale: 1.65,
    dumanModelContextScale: 0.266,
    interiorDirection: [1, 0.35, 0.3] as [number, number, number],
    interiorTargetOffset: [0, -2, 0] as [number, number, number],
    interiorFitScale: 0.28,
    interiorFov: 58,
    waypoints: {
      doorApproach: {
        position: [96, 138, 49] as [number, number, number],
        target: [16, 116, 64] as [number, number, number],
        fov: 46,
      },
      doorThreshold: {
        position: [45, 134, 49] as [number, number, number],
        target: [-16, 116, 69] as [number, number, number],
        fov: 54,
      },
      exitThreshold: {
        position: [62, 136, 49] as [number, number, number],
        target: [3, 118, 67] as [number, number, number],
        fov: 50,
      },
      dumanApproach: {
        position: [240, 200, 210] as [number, number, number],
        target: [20, 120, 105] as [number, number, number],
        fov: 34,
      },
    },
    paths: {
      heroToInterior: [
        { waypoint: 'doorApproach', duration: 0.95 },
        { waypoint: 'doorThreshold', duration: 0.65 },
        { waypoint: 'interior', duration: 1 },
      ],
      interiorToDuman: [
        { waypoint: 'exitThreshold', duration: 1.05 },
        { waypoint: 'dumanApproach', duration: 1.25 },
        { waypoint: 'dumanFinal', duration: 1.3 },
      ],
    },
    minimumOrbitDistanceScale: 0.04,
  },
  environment: {
    resolution: 256,
    intensity: 1.15,
    hemisphereIntensity: 0.42,
    keyLightIntensity: 1.1,
    fillLightIntensity: 0.28,
    rimLightIntensity: 0.65,
    directionalLights: [
      { position: [5, 8, 7] as [number, number, number], color: '#fffdf5' },
      { position: [-6, 3, 4] as [number, number, number], color: '#ecece5' },
      { position: [1, 5, -7] as [number, number, number], color: '#f5f4ef' },
    ],
    softboxes: [
      {
        name: 'vertical-key',
        color: '#fffdf7',
        intensity: 8.5,
        position: [5, 0.6, 1.5] as [number, number, number],
        scale: [2.2, 4.5] as [number, number],
      },
      {
        name: 'vertical-contrast',
        color: '#747873',
        intensity: 0.35,
        position: [-4, 0.5, 2] as [number, number, number],
        scale: [0.8, 3.6] as [number, number],
      },
      {
        name: 'overhead-fill',
        color: '#f2f1eb',
        intensity: 3.8,
        position: [0, 5, -1] as [number, number, number],
        scale: [2.6, 1.1] as [number, number],
      },
      {
        name: 'rear-strip',
        color: '#d7d9d4',
        intensity: 4.6,
        position: [0, 0, -5] as [number, number, number],
        scale: [4.2, 0.55] as [number, number],
      },
    ],
  },
}
